### ISSUE TITLE
Factor language not working

### ISSUE THREAD

**Issue by chunes3** [attempt-this-online/attempt-this-online#113]
Running a hello world program gives the following output on stderr:

```
/ATO/runner: line 6:     3 Killed                  /ATO/yargs %1 /ATO/options /ATO/yargs %2 /ATO/arguments /opt/factor/factor %1 /ATO/code %2 < /ATO/input
```

**Comment by pxeger** [comment]
No longer reproducible. I had a bunch of transient errors last week which were suspicious but I don't have any way to diagnose them at the moment.
