### ISSUE TITLE
Font ligature demo has to be toggled twice to be visible

### ISSUE THREAD

**Issue by ysthakur** [attempt-this-online/attempt-this-online#12]
In the preferences section, the font ligature demo looks like normal text even when it's on. You need to turn it off and on again for it to show up.

**Comment by pxeger** [comment]
Yep, this is a known issue. Unfortunately bugs in the preferences which are saved to localforage are quite hard to debug because Firefox DevTools' IndexedDB viewer <s>is</s> *was until recently* broken.

**Comment by pxeger** [comment]
Actually, Firefox DevTools' IndexedDB viewer seems to still be broken on localhost URLs.

**Comment by pxeger** [comment]
Note to self: I fixed this by setting `window.localForage = localForage` to allow myself to edit IndexedDB in the browser console.
