### ISSUE TITLE
Clicking "Execute" hangs for any language, any program

### ISSUE THREAD

**Issue by mbomb007** [attempt-this-online/attempt-this-online#122]
When trying to run any program with any language, even an empty program, I get this error in my browser console, and the page hangs.

> WebSocket connection to 'wss://ato.pxeger.com/api/v1/ws/execute' failed

I cannot even click the "Kill" button.

**Comment by pxeger** [comment]
Yep, ATO was down for a few hours - sorry about that. In future you can use https://staging.ato.pxeger.com instead - one of them will usually be working.
