### ISSUE TITLE
Don't show ASCII arrows as ligature

### ISSUE THREAD

**Issue by jxu** [attempt-this-online/attempt-this-online#128]
I'm not sure what causes this ligature, but it's highly annoying and misleading as it looks like a unicode character or something.

Typing `<-` shows up as 
![image](https://github.com/attempt-this-online/attempt-this-online/assets/7989982/7a94e5ae-992c-476b-8c84-f35c165e07c0)

**Comment by pxeger** [comment]
Go to [Preferences](https://ato.pxeger.com/preferences) and turn off Font Ligatures.
