### ISSUE TITLE
Request: Upgrade to Python 3.13

### ISSUE THREAD

**Issue by blhsing** [attempt-this-online/attempt-this-online#153]
Python 3.13 was released a month ago on 10/07/2024 with several important new features. It would be great if ATO could upgrade Python to the latest version. Thanks!

**Comment by pxeger** [comment]
Live on staging: https://staging.ato.pxeger.com/run?1=m72soLIkIz9vbbSSrm5ZalFxZn6eUuyCpaUlaboWaBSUBgA
