### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by ysthakur** [attempt-this-online/attempt-this-online#27]
Basic syntax highlighting using [highlight.js](https://highlightjs.org/) or something would be nice. Custom syntax highlighters could also be made for languages that aren't supported by highlight.js/whatever or need better syntax highlighting, although maybe that would have to be opt-in.

Not a priority, but it would be nice to have.

**Comment by pxeger** [comment]
#21 
Please check for existing issues
