### ISSUE TITLE
CBQN produces console error

### ISSUE THREAD

**Issue by ajc2** [attempt-this-online/attempt-this-online#53]
Running anything in CBQN produces this error in the console and the code will not run.
```
Uncaught Error: websocket connection unexpectedly closed with code 1011
    at WebSocket.o.mark.o.wrap.l.onclose (_app-e942a41a5bbdebff.js:1:36010)
Error: websocket connection unexpectedly closed with code 1011
    at WebSocket.o.mark.o.wrap.l.onclose (_app-e942a41a5bbdebff.js:1:36010)
```
Tested with both Vivaldi on Linux and Android.

**Comment by pxeger** [comment]
Running anything in anything produces this error

more details: https://chat.stackexchange.com/transcript/240?m=60991249#60991249

**Comment by pxeger** [comment]
Sorry, I was wrong. Something apparently went wrong with the installation process, and BQN, Python, Ruby, Scala 2, and `///` didn't get installed. I'm working on it

**Comment by pxeger** [comment]
BQN is fixed. Some others are still broken but I'll fix them later.
