### ISSUE TITLE
Uncaught Error: websocket connection unexpectedly closed with code 1011

### ISSUE THREAD

**Issue by HoangTuan110** [attempt-this-online/attempt-this-online#54]
For some reason, when running Ruby code, I got this error:

```
Uncaught Error: websocket connection unexpectedly closed with code 1011
```

![Screenshot](https://files.catbox.moe/corl52.png)
[Link to code](https://ato.pxeger.com/run?1=m72kqDSpcsGCpaUlaboWKwtKS4oVlEwNlCB8qDBMGgA)

This seems to happened only with Ruby.

**Comment by pxeger** [comment]
Duplicate of #53 but for Ruby. Now fixed.
