### ISSUE TITLE
Language request: Vyxal

### ISSUE THREAD

**Issue by Lyxal** [attempt-this-online/attempt-this-online#6]
This is for when you do start adding more languages.

Link: https://github.com/Vyxal/Vyxal

**Comment by pxeger** [comment]
https://chat.stackexchange.com/transcript/message/58463538#58463538

**Comment by Lyxal** [comment]
Protip: you can make a post request to https://www.lyxal.pythonanywhere.com/execute with the appropriate fields and it'll return the evaluated code. That's what hyper's chat bot does.

**Comment by pxeger** [comment]
Thanks, but I want to stick with always running the code on the ATO server.

**Comment by Lyxal** [comment]
cool cool.

**Comment by Lyxal** [comment]
https://github.com/attempt-this-online/languages/blob/main/languages/vyxal/Dockerfile

Kekw this needs to be updated to v2.7.2+ and also the todo in the file is now done too

**Comment by pxeger** [comment]
Using Poetry does simplify Vyxal's packaging quite a lot, that's true. I'll get on it soon, I promise!

**Comment by cgccuser** [comment]
Ah, so *that's* why you were so keen to move to Poetry

**Comment by Lyxal** [comment]
Cries in 279 days and still not added 😭

**Comment by pxeger** [comment]
In fact it will™ literally be done this weekend. I was working on it in the batch of languages I added yesterday; unfortunately it just took ever so slightly longer than I expected so I didn't get it quite done then, but I promise you I will attempt to get this online

**Comment by pxeger** [comment]
Hmm, [it works](https://staging.ato.pxeger.com/run?1=m720rLIiMWfBgqWlJWm6FuuNFIwVtBUSMlJzcvITFLQgolBJmCIA), but [only kind of](https://staging.ato.pxeger.com/run?1=m720rLIiMWdptFKWUuyCpaUlaboWOx81NR6b_aip91FT86Om1my3Q3u1HnVMfNSxBSIPVbYASgMA)

**Comment by pxeger** [comment]
https://chat.stackexchange.com/transcript/message/60351761#60351761

fixed by cac333d42d8f87d171f0d1d92a198d08e764a410
