### ISSUE TITLE
Pyth does not work

### ISSUE THREAD

**Issue by Mukundan314** [attempt-this-online/attempt-this-online#82]
Currently pyth does not work properly: https://ato.pxeger.com/run?1=m72koLIkY8GCpaUlaboWK3OUSlKLSzLz0iF8qDBMGgA
This is probably because pyth does not support being run on python >=3.8. Could the python interpreter being used by pyth be downgraded?

**Comment by Steffan153** [comment]
Anything <= 3.9 should work, because `collections.Iterable` was removed in 3.10.

**Comment by pxeger** [comment]
Now fixed
