### ISSUE TITLE
Link formatting templates

### ISSUE THREAD

**Issue by pxeger** [attempt-this-online/attempt-this-online#9]
TIO has the following:
- Plain link
- HTML
- Wiki markup
- Markdown link
- Code Golf submission (Stack Exchange)
- BBCode

Maybe offer customisable templates? (too complicated?) Or just the option to show/hide which options are there?

**Comment by ysthakur** [comment]
Customizable templates sound like a lot of trouble, but having non-CGCC submission templates accessible by hitting a button and letting them slide out would be nice.

**Comment by pxeger** [comment]
Recently I've added a new UI for copying to clipboard, including the addition of a CMC format button.

It will now be much easier to implement new templates, so I'm closing this issue; if you want any others, please open a new issue.
